par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
plot(subdata$Global_active_power ~ Datetime, type = "l",ylab = "Global Active Power (kilowatts)", xlab = "")
plot(subdata$Voltage ~ Datetime,  type = "l", ylab = "Voltage", xlab = "datetime")
with(subdata, {
  plot(Sub_metering_1 ~ Datetime, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
  lines(Sub_metering_2 ~ Datetime, col = 'Red')
  lines(Sub_metering_3 ~ Datetime, col = 'Blue')
})
legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 1,  bty = "n", cex=0.4, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(subdata$Global_reactive_power ~ Datetime,  type = "l", ylab = "Global_rective_power", xlab = "datetime")
dev.copy(png,'plot4.png', width = 480, height = 480)
dev.off()